import 'package:flutter/foundation.dart';
import '../models/active_program_model.dart';

class ProgramProvider extends ChangeNotifier {
  List<ProgramInfo> _programs = [
    ProgramInfo(
      pid: 303,
      name: "Terminal",
      cpuUsage: 3.1,
      memoryUsage: 200000,
      executablePath: "/System/Applications/Utilities/Terminal.app",
      startTime: DateTime.now().subtract(const Duration(minutes: 45)),
      threadCount: 10,
      parentPid: 1,
      user: "John Doe",
      diskRead: 300,
      diskWrite: 150,
      state: "Running",
      windowTitle: "Terminal",
    ),
    ProgramInfo(
      pid: 101,
      name: "Google Chrome",
      cpuUsage: 12.5,
      memoryUsage: 512000,
      executablePath: "/Applications/Google Chrome.app",
      startTime: DateTime.now().subtract(const Duration(hours: 2)),
      threadCount: 34,
      parentPid: 1,
      user: "John Doe",
      diskRead: 500,
      diskWrite: 200,
      state: "Running",
      windowTitle: "Chrome Browser",
    ),
    ProgramInfo(
      pid: 303,
      name: "Terminal",
      cpuUsage: 3.1,
      memoryUsage: 200000,
      executablePath: "/System/Applications/Utilities/Terminal.app",
      startTime: DateTime.now().subtract(const Duration(minutes: 45)),
      threadCount: 10,
      parentPid: 1,
      user: "John Doe",
      diskRead: 300,
      diskWrite: 150,
      state: "Running",
      windowTitle: "Terminal",
    ),
    ProgramInfo(
      pid: 303,
      name: "Terminal",
      cpuUsage: 3.1,
      memoryUsage: 200000,
      executablePath: "/System/Applications/Utilities/Terminal.app",
      startTime: DateTime.now().subtract(const Duration(minutes: 45)),
      threadCount: 10,
      parentPid: 1,
      user: "John Doe",
      diskRead: 300,
      diskWrite: 150,
      state: "Running",
      windowTitle: "Terminal",
    ),
    ProgramInfo(
      pid: 202,
      name: "VS Code",
      cpuUsage: 8.2,
      memoryUsage: 800000,
      executablePath: "/Applications/Visual Studio Code.app",
      startTime: DateTime.now().subtract(const Duration(hours: 3)),
      threadCount: 50,
      parentPid: 1,
      user: "John Doe",
      diskRead: 700,
      diskWrite: 400,
      state: "Running",
      windowTitle: "VS Code - main.dart",
    ),
    ProgramInfo(
      pid: 101,
      name: "Google Chrome",
      cpuUsage: 12.5,
      memoryUsage: 512000,
      executablePath: "/Applications/Google Chrome.app",
      startTime: DateTime.now().subtract(const Duration(hours: 2)),
      threadCount: 34,
      parentPid: 1,
      user: "John Doe",
      diskRead: 500,
      diskWrite: 200,
      state: "Running",
      windowTitle: "Chrome Browser",
    ),
    ProgramInfo(
      pid: 303,
      name: "Terminal",
      cpuUsage: 3.1,
      memoryUsage: 200000,
      executablePath: "/System/Applications/Utilities/Terminal.app",
      startTime: DateTime.now().subtract(const Duration(minutes: 45)),
      threadCount: 10,
      parentPid: 1,
      user: "John Doe",
      diskRead: 300,
      diskWrite: 150,
      state: "Running",
      windowTitle: "Terminal",
    ),
    ProgramInfo(
      pid: 101,
      name: "Google Chrome",
      cpuUsage: 12.5,
      memoryUsage: 512000,
      executablePath: "/Applications/Google Chrome.app",
      startTime: DateTime.now().subtract(const Duration(hours: 2)),
      threadCount: 34,
      parentPid: 1,
      user: "John Doe",
      diskRead: 500,
      diskWrite: 200,
      state: "Running",
      windowTitle: "Chrome Browser",
    ),
    ProgramInfo(
      pid: 303,
      name: "Terminal",
      cpuUsage: 3.1,
      memoryUsage: 200000,
      executablePath: "/System/Applications/Utilities/Terminal.app",
      startTime: DateTime.now().subtract(const Duration(minutes: 45)),
      threadCount: 10,
      parentPid: 1,
      user: "John Doe",
      diskRead: 300,
      diskWrite: 150,
      state: "Running",
      windowTitle: "Terminal",
    ),
    ProgramInfo(
      pid: 101,
      name: "Google Chrome",
      cpuUsage: 12.5,
      memoryUsage: 512000,
      executablePath: "/Applications/Google Chrome.app",
      startTime: DateTime.now().subtract(const Duration(hours: 2)),
      threadCount: 34,
      parentPid: 1,
      user: "John Doe",
      diskRead: 500,
      diskWrite: 200,
      state: "Running",
      windowTitle: "Chrome Browser",
    ),
    ProgramInfo(
      pid: 101,
      name: "Google Chrome",
      cpuUsage: 12.5,
      memoryUsage: 512000,
      executablePath: "/Applications/Google Chrome.app",
      startTime: DateTime.now().subtract(const Duration(hours: 2)),
      threadCount: 34,
      parentPid: 1,
      user: "John Doe",
      diskRead: 500,
      diskWrite: 200,
      state: "Running",
      windowTitle: "Chrome Browser",
    ),
    ProgramInfo(
      pid: 101,
      name: "Google Chrome",
      cpuUsage: 12.5,
      memoryUsage: 512000,
      executablePath: "/Applications/Google Chrome.app",
      startTime: DateTime.now().subtract(const Duration(hours: 2)),
      threadCount: 34,
      parentPid: 1,
      user: "John Doe",
      diskRead: 500,
      diskWrite: 200,
      state: "Running",
      windowTitle: "Chrome Browser",
    ),
    ProgramInfo(
      pid: 101,
      name: "Google Chrome",
      cpuUsage: 12.5,
      memoryUsage: 512000,
      executablePath: "/Applications/Google Chrome.app",
      startTime: DateTime.now().subtract(const Duration(hours: 2)),
      threadCount: 34,
      parentPid: 1,
      user: "John Doe",
      diskRead: 500,
      diskWrite: 200,
      state: "Running",
      windowTitle: "Chrome Browser",
    ),
    ProgramInfo(
      pid: 101,
      name: "Google Chrome",
      cpuUsage: 12.5,
      memoryUsage: 512000,
      executablePath: "/Applications/Google Chrome.app",
      startTime: DateTime.now().subtract(const Duration(hours: 2)),
      threadCount: 34,
      parentPid: 1,
      user: "John Doe",
      diskRead: 500,
      diskWrite: 200,
      state: "Running",
      windowTitle: "Chrome Browser",
    ),
    ProgramInfo(
      pid: 101,
      name: "Google Chrome",
      cpuUsage: 12.5,
      memoryUsage: 512000,
      executablePath: "/Applications/Google Chrome.app",
      startTime: DateTime.now().subtract(const Duration(hours: 2)),
      threadCount: 34,
      parentPid: 1,
      user: "John Doe",
      diskRead: 500,
      diskWrite: 200,
      state: "Running",
      windowTitle: "Chrome Browser",
    ),
    ProgramInfo(
      pid: 101,
      name: "Google Chrome",
      cpuUsage: 12.5,
      memoryUsage: 512000,
      executablePath: "/Applications/Google Chrome.app",
      startTime: DateTime.now().subtract(const Duration(hours: 2)),
      threadCount: 34,
      parentPid: 1,
      user: "John Doe",
      diskRead: 500,
      diskWrite: 200,
      state: "Running",
      windowTitle: "Chrome Browser",
    ),
    ProgramInfo(
      pid: 101,
      name: "Google Chrome",
      cpuUsage: 12.5,
      memoryUsage: 512000,
      executablePath: "/Applications/Google Chrome.app",
      startTime: DateTime.now().subtract(const Duration(hours: 2)),
      threadCount: 34,
      parentPid: 1,
      user: "John Doe",
      diskRead: 500,
      diskWrite: 200,
      state: "Running",
      windowTitle: "Chrome Browser",
    ),
  ];

  List<ProgramInfo> get programs => _programs;

  /// Function to update the program list (will be called after fetching data from C++)
  void updatePrograms(List<ProgramInfo> newPrograms) {
    _programs = newPrograms;
    notifyListeners();
  }
}
